#
# Baking!
#

# ------------------------------------------------------------------------------
# Input files
# ------------------------------------------------------------------------------
EXECUTABLE      := multiGPU

HSMAIN          := multiGPU.hs
CUFILES         := simpleMultiGPU_kernel.cu

EXTRALIBS       := stdc++
GHCFLAGS	+= -threaded

# ------------------------------------------------------------------------------
# Haskell/CUDA build system
# ------------------------------------------------------------------------------
include ../../common/common.mk

